# Generated by Django 4.1.13 on 2026-01-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_App', '0005_alter_userdetails_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
